version: '3.8'

services:
  nginx:
    container_name: nginx_demo
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./bedrock/web:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - wordpress

  wordpress:
    container_name: wp_demo
    image: wordpress:php8.3-fpm # use the most recent compatible wp
    volumes:
      - ./bedrock/vendor:/var/www/vendor 
      - ./bedrock/config:/var/www/config 
      - ./bedrock/web:/var/www/html
    environment:
      # same crendencials from.env
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: demo 
      WORDPRESS_DB_PASSWORD: demo
      WORDPRESS_DB_NAME: demo
    depends_on:
      - db
    restart: always

  db:
    container_name: db_demo
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # same crendencials from.env
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    restart: always

volumes:
  db_data:
